title: Home Server
description: kaungkhantko home lab
startUrl: https://home.tailc65fb0.ts.net:8443

background:
  blur: sm
  opacity: 50

theme: dark
color: slate

useEqualHeights: true

layout:
  Media:
    style: row
    columns: 4
  Downloads:
    style: row
    columns: 4
  Finance:
    style: row
    columns: 3
  System:
    style: row
    columns: 4
